In [4]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [5]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
dates = pd.date_range('20130101',periods = 6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(6,4),index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  1.043058 -0.164872 -1.612330  0.235259
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-04 -0.903428 -0.676502  0.516694  2.611231
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506

In [17]:
df2 = pd.DataFrame( { 'A' : 1.,
                    'B' : pd.date_range('20160101',periods=4),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4, dtype='int32'),
                    'E' : pd.Categorical(['test','train','valid','filibuster']),
                    'F' : 'foo'})
df2

A          B    C  D           E    F
0  1.0 2016-01-01  1.0  3        test  foo
1  1.0 2016-01-02  1.0  3       train  foo
2  1.0 2016-01-03  1.0  3       valid  foo
3  1.0 2016-01-04  1.0  3  filibuster  foo

In [18]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [28]:
print(df.head(2))
print(df.tail(2))

                   A         B         C         D
2013-01-01  1.043058 -0.164872 -1.612330  0.235259
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
                   A         B         C         D
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506


In [35]:
# index
print('index',df.index)
# columns
print('columns',df.columns)
# values
print('values',df.values)

index DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
columns Index(['A', 'B', 'C', 'D'], dtype='object')
values [[ 1.04305842 -0.16487163 -1.6123301   0.23525897]
 [-0.92006423  0.49885979 -0.77580695 -0.54109399]
 [ 0.10340659 -0.60022212  0.9671697  -1.47285637]
 [-0.90342758 -0.67650221  0.51669375  2.61123066]
 [ 0.23566067  0.84298914  2.58532193  1.41633681]
 [-0.83122149 -0.22146769  1.01927946 -1.04150595]]


In [36]:
# STATISTICS
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.212098 -0.053536  0.450055  0.201228
std    0.804725  0.606044  1.477254  1.561009
min   -0.920064 -0.676502 -1.612330 -1.472856
25%   -0.885376 -0.505534 -0.452682 -0.916403
50%   -0.363907 -0.193170  0.741932 -0.152918
75%    0.202597  0.332927  1.006252  1.121067
max    1.043058  0.842989  2.585322  2.611231

In [37]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [38]:
# transpose
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.043058   -0.920064    0.103407   -0.903428    0.235661   -0.831221
B   -0.164872    0.498860   -0.600222   -0.676502    0.842989   -0.221468
C   -1.612330   -0.775807    0.967170    0.516694    2.585322    1.019279
D    0.235259   -0.541094   -1.472856    2.611231    1.416337   -1.041506

In [44]:
print(df)
print(df.sort_index(axis=0,ascending=False))
df.sort_index(axis=1,ascending=False)

                   A         B         C         D
2013-01-01  1.043058 -0.164872 -1.612330  0.235259
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-04 -0.903428 -0.676502  0.516694  2.611231
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506
                   A         B         C         D
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-04 -0.903428 -0.676502  0.516694  2.611231
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-01  1.043058 -0.164872 -1.612330  0.235259


D         C         B         A
2013-01-01  0.235259 -1.612330 -0.164872  1.043058
2013-01-02 -0.541094 -0.775807  0.498860 -0.920064
2013-01-03 -1.472856  0.967170 -0.600222  0.103407
2013-01-04  2.611231  0.516694 -0.676502 -0.903428
2013-01-05  1.416337  2.585322  0.842989  0.235661
2013-01-06 -1.041506  1.019279 -0.221468 -0.831221

In [46]:
df.sort_values(by='B',ascending=False)

A         B         C         D
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-01  1.043058 -0.164872 -1.612330  0.235259
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-04 -0.903428 -0.676502  0.516694  2.611231

In [53]:
# selection
print(df[1:3])
print(df['A'])

                   A         B         C         D
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-01    1.043058
2013-01-02   -0.920064
2013-01-03    0.103407
2013-01-04   -0.903428
2013-01-05    0.235661
2013-01-06   -0.831221
Freq: D, Name: A, dtype: float64


In [54]:
df['20130102':'20130105']

A         B         C         D
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-04 -0.903428 -0.676502  0.516694  2.611231
2013-01-05  0.235661  0.842989  2.585322  1.416337

In [59]:
# selection by label
print(df['20130103':'20130103'])
print(df.loc[dates[2]])
print(df.loc['20130103'])

                   A         B        C         D
2013-01-03  0.103407 -0.600222  0.96717 -1.472856
A    0.103407
B   -0.600222
C    0.967170
D   -1.472856
Name: 2013-01-03 00:00:00, dtype: float64
A    0.103407
B   -0.600222
C    0.967170
D   -1.472856
Name: 2013-01-03 00:00:00, dtype: float64


In [64]:
# multi-axis by label
df.loc[:,['B','C']]

B         C
2013-01-01 -0.164872 -1.612330
2013-01-02  0.498860 -0.775807
2013-01-03 -0.600222  0.967170
2013-01-04 -0.676502  0.516694
2013-01-05  0.842989  2.585322
2013-01-06 -0.221468  1.019279

In [66]:
df.loc['20130102':'20130105',['A','D']]

A         D
2013-01-02 -0.920064 -0.541094
2013-01-03  0.103407 -1.472856
2013-01-04 -0.903428  2.611231
2013-01-05  0.235661  1.416337

In [67]:
df.loc['20130104',['A','B']]

A   -0.903428
B   -0.676502
Name: 2013-01-04 00:00:00, dtype: float64

In [68]:
df.loc['20130104','A']

-0.90342758256030375

In [71]:
# get scalar using at
df.at[dates[3],'A']

-0.90342758256030375

In [73]:
# selection by position
df.iloc[3]

A   -0.903428
B   -0.676502
C    0.516694
D    2.611231
Name: 2013-01-04 00:00:00, dtype: float64

In [76]:
df.iloc[2:,2:] # row slice, column slice

C         D
2013-01-03  0.967170 -1.472856
2013-01-04  0.516694  2.611231
2013-01-05  2.585322  1.416337
2013-01-06  1.019279 -1.041506

In [77]:
# get a scalar
df.iloc[3,3]

2.6112306563911152

In [78]:
# faster access : get a scalar
df.iat[3,3]

2.6112306563911152

In [80]:
# Boolean indexing
df[df.A > 0]

A         B         C         D
2013-01-01  1.043058 -0.164872 -1.612330  0.235259
2013-01-03  0.103407 -0.600222  0.967170 -1.472856
2013-01-05  0.235661  0.842989  2.585322  1.416337

In [81]:
df[df > 0]

A         B         C         D
2013-01-01  1.043058       NaN       NaN  0.235259
2013-01-02       NaN  0.498860       NaN       NaN
2013-01-03  0.103407       NaN  0.967170       NaN
2013-01-04       NaN       NaN  0.516694  2.611231
2013-01-05  0.235661  0.842989  2.585322  1.416337
2013-01-06       NaN       NaN  1.019279       NaN

In [91]:
df1 = df.copy()
df1['E'] = ['one', 'one','two','three','four','three']
df1[ df1['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  0.103407 -0.600222  0.967170 -1.472856   two
2013-01-05  0.235661  0.842989  2.585322  1.416337  four

In [93]:
df2[ df2.E.isin(['valid','test'])]

A          B    C  D      E    F
0  1.0 2016-01-01  1.0  3   test  foo
2  1.0 2016-01-03  1.0  3  valid  foo

In [99]:
# add new column
s1 = pd.Series( [1,2,3,4,5,7], index=pd.date_range('20130101',periods=6))
s1

2013-01-01    1
2013-01-02    2
2013-01-03    3
2013-01-04    4
2013-01-05    5
2013-01-06    7
Freq: D, dtype: int64

In [100]:
df['E'] = s1
df

A         B         C         D  E
2013-01-01  1.043058 -0.164872 -1.612330  0.235259  1
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094  2
2013-01-03  0.103407 -0.600222  0.967170 -1.472856  3
2013-01-04 -0.903428 -0.676502  0.516694  2.611231  4
2013-01-05  0.235661  0.842989  2.585322  1.416337  5
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506  7

In [101]:
# setting values
df.loc['20130104','A'] = 8.8888
df

A         B         C         D  E
2013-01-01  1.043058 -0.164872 -1.612330  0.235259  1
2013-01-02 -0.920064  0.498860 -0.775807 -0.541094  2
2013-01-03  0.103407 -0.600222  0.967170 -1.472856  3
2013-01-04  8.888800 -0.676502  0.516694  2.611231  4
2013-01-05  0.235661  0.842989  2.585322  1.416337  5
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506  7

In [103]:
# by position
df.iat[1,1] = 0.1234567
df

A         B         C         D  E
2013-01-01  1.043058 -0.164872 -1.612330  0.235259  1
2013-01-02 -0.920064  0.123457 -0.775807 -0.541094  2
2013-01-03  0.103407 -0.600222  0.967170 -1.472856  3
2013-01-04  8.888800 -0.676502  0.516694  2.611231  4
2013-01-05  0.235661  0.842989  2.585322  1.416337  5
2013-01-06 -0.831221 -0.221468  1.019279 -1.041506  7

In [106]:
# setting a numpy array
df.D = np.array([2]*len(df))
df

A         B         C  D  E
2013-01-01  1.043058 -0.164872 -1.612330  2  1
2013-01-02 -0.920064  0.123457 -0.775807  2  2
2013-01-03  0.103407 -0.600222  0.967170  2  3
2013-01-04  8.888800 -0.676502  0.516694  2  4
2013-01-05  0.235661  0.842989  2.585322  2  5
2013-01-06 -0.831221 -0.221468  1.019279  2  7

In [108]:
# setting with where condition
df[df > 0] = -df
df

A         B         C  D  E
2013-01-01 -1.043058 -0.164872 -1.612330 -2 -1
2013-01-02 -0.920064 -0.123457 -0.775807 -2 -2
2013-01-03 -0.103407 -0.600222 -0.967170 -2 -3
2013-01-04 -8.888800 -0.676502 -0.516694 -2 -4
2013-01-05 -0.235661 -0.842989 -2.585322 -2 -5
2013-01-06 -0.831221 -0.221468 -1.019279 -2 -7

# Missing Data

In [126]:
print(df)
#df.iat[3,3] = np.nan
df.iat[2,2] = np.nan
df.iat[1,1] = np.nan
df.iat[0,0] = np.nan
df

                   A         B         C  D  E
2013-01-01 -1.043058 -0.164872 -1.612330 -2 -1
2013-01-02 -0.920064       NaN -0.775807 -2 -2
2013-01-03 -0.103407 -0.600222       NaN -2 -3
2013-01-04 -8.888800 -0.676502 -0.516694 -2 -4
2013-01-05 -0.235661 -0.842989 -2.585322 -2 -5
2013-01-06 -0.831221 -0.221468 -1.019279 -2 -7


A         B         C  D  E
2013-01-01       NaN -0.164872 -1.612330 -2 -1
2013-01-02 -0.920064       NaN -0.775807 -2 -2
2013-01-03 -0.103407 -0.600222       NaN -2 -3
2013-01-04 -8.888800 -0.676502 -0.516694 -2 -4
2013-01-05 -0.235661 -0.842989 -2.585322 -2 -5
2013-01-06 -0.831221 -0.221468 -1.019279 -2 -7

In [130]:
df.dropna()

A         B         C  D  E
2013-01-04 -8.888800 -0.676502 -0.516694 -2 -4
2013-01-05 -0.235661 -0.842989 -2.585322 -2 -5
2013-01-06 -0.831221 -0.221468 -1.019279 -2 -7

In [131]:
df.fillna(9.87654321)

A         B         C  D  E
2013-01-01  9.876543 -0.164872 -1.612330 -2 -1
2013-01-02 -0.920064  9.876543 -0.775807 -2 -2
2013-01-03 -0.103407 -0.600222  9.876543 -2 -3
2013-01-04 -8.888800 -0.676502 -0.516694 -2 -4
2013-01-05 -0.235661 -0.842989 -2.585322 -2 -5
2013-01-06 -0.831221 -0.221468 -1.019279 -2 -7

## Get a boolean mask where values are nan

In [133]:
df.isnull() # or pd.isnull(df)

A      B      C      D      E
2013-01-01   True  False  False  False  False
2013-01-02  False   True  False  False  False
2013-01-03  False  False   True  False  False
2013-01-04  False  False  False  False  False
2013-01-05  False  False  False  False  False
2013-01-06  False  False  False  False  False